accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('delete/', views.delete, name="delete"),
    path('password/', views.password, name="password"),
    path('<int:user_id>/follow/', views.follow, name="follow")
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_view
from posts import views as posts_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_view.people, name="people"),
    path('', posts_view.list, name="root"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.list, name='list'),
    path('<int:post_num>/delete/', views.delete, name="delete"),
    path('<int:post_num>/update/', views.update, name="update"),
    path('<int:post_num>/like/', views.like, name="like"),
    path('<int:post_num>/comment/create/', views.create_comment, name="create_comment"),
    path('<int:post_num>/comment/<int:comment_num>/delete/', views.delete_comment, name="delete_comment"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=30, blank=True)
    profile_image = models.ImageField(blank=True, default='default.jpg')
    
    
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")
    

posts/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    
class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'nickname', 'profile_image']
        
        
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from .forms import CustomUserChangeForm, ProfileForm, CustomUserCreationForm
from .models import Profile


# Create your views here.
def login(request):
    if request.method == "POST":
        #로그인 검증
        # username = request.POST.get('username')
        # password = request.POST.get('password')
        
        # login_user = authenticate(request, username=username, password=password)
        
        # 더 쉬운 방법
        form = AuthenticationForm(request, request.POST)
        
        if form.is_valid():
            auth_login(request, form.get_user())
            
            # GET으로 들어온 값중 'next'가 가진 값을 가져온다
            # next가 저의되어 있으면 해당 url로 redirect
            # else: post:list로 redirect
            return redirect(request.GET.get('next') or 'posts:list')
        #로그인 시킨다
        # if login_user is not None:
        #     auth_login(request, login_user)
        #     return redirect('posts:list')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    
    return redirect('posts:list')
    
    
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('posts:list')
    else:
        form = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})
        
        
def people(request, username):
    # information about user
    people = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/people.html', { 'people': people })
    

# change account information(editting & updating)
# @login_required
def update(request):
    if request.method == "POST":
        # updating
        user_change_form = CustomUserChangeForm(data=request.POST, instance=request.user)
        profile_form = ProfileForm(data=request.POST, files=request.FILES, instance=request.user.profile)

        if user_change_form.is_valid() and profile_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect('people', user.username)
        
    else:
        # editting
        user_change_form = CustomUserChangeForm(instance=request.user)
        
        # 1. instance에 넣어줄 profile이 있는 user와 없는 user가 있다
        profile, created = Profile.objects.get_or_create(user=request.user)
        
        profile_form = ProfileForm(instance=profile)
        
        context = {
            'user_change_form': user_change_form,
            'profile_form': profile_form,
        }
        
        return render(request, 'accounts/update.html', context)
        
        
def delete(request):
    if request.method == "POST":
        request.user.delete()
        return redirect('accounts:signup')
    
    return render(request, 'accounts/delete.html')
    

def password(request):
    if request.method == "POST":
        password_change_form = PasswordChangeForm(request.user, request.POST)
        
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
        
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
        context = {
            'password_change_form': password_change_form
        }
        
        return render(request, 'accounts/password.html', context)
    
    
def follow(request, user_id):
    follower = get_object_or_404(get_user_model(), pk=user_id)
    
    # 만약 현재 유저가 해당 유저를 이미 팔로우 하고 있다면
    # 팔로우 취소
    if request.user != follower:
        if request.user in follower.followers.all() :
            follower.followers.remove(request.user)
        else:
            follower.followers.add(request.user)
    
    return redirect('people', follower.username)

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <p>정말로 탈퇴하시겠습니까? ㅠㅠ</p>
        <button class="btn btn-info">아니요</button>
        <button class="btn btn-danger">예</button>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h2> sign - in </h2>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">login</button>
</form>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h2> Change Password </h2>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form password_change_form %}

  <button type="submit" class="btn btn-primary">비밀번호 수정</button>
</form>
{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}


{% block body %}

<img src="{{ people.profile.profile_image.url }}" style="width:100px; height:100px; border-radius: 50%;">


<h1>{{ people.username }}

{% if user in people.followers.all %}
<a href="{% url 'accounts:follow' people.id %}" class="btn btn-primary">Follow</a>
{% else %}
<a href="{% url 'accounts:follow' people.id %}" class="btn btn-outline-primary">Unfollow</a>
{% endif %}
</h1>

<p>{{ people.last_name }} {{ people.first_name }}</p>
<p><strong>{{ people.profile.nickname }}</strong></p>
<p>{{ people.followers.count }}</p>


<p>
  {{ people.profile.description }}
</p>

{% if user == people %}
<a href="{% url 'accounts:update' %}" class="btn btn-info">회원정보 수정</a>
{% endif %}

{% if user == people %}
<a href="{% url 'accounts:password' %}" class="btn btn-info">비밀번호 수정</a>
{% endif %}

{% if user == people %}
<a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원 탈퇴</a>
{% endif %}

<div class="row mt-3">
  {% for post in people.post_set.all %}
    <div class="col-4">
      <img src="{{ post.image.url }}" class="img-fluid">
    </div>
  {% endfor %}
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h2> sign - up </h2>
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">login</button>
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<h2> Change Information </h2>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form user_change_form %}
  {% bootstrap_form profile_form %}

  <button type="submit" class="btn btn-primary">정보 수정</button>
</form>
{% endblock %}