instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_view
from posts import views as posts_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_view.people, name="people"),
    path('', posts_view.list, name="root"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.list, name='list'),
    path('<int:post_num>/delete/', views.delete, name="delete"),
    path('<int:post_num>/update/', views.update, name="update"),
    path('<int:post_num>/like/', views.like, name="like"),
    path('<int:post_num>/comment/create/', views.create_comment, name="create_comment"),
    path('<int:post_num>/comment/<int:comment_num>/delete/', views.delete_comment, name="delete_comment"),
]

posts/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    
class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment

# PostModelForm definition for contrall Post
class PostForm(forms.ModelForm):
    # 1. which input field
    content = forms.CharField(label="content", widget=forms.Textarea(attrs={
        'placeholder': "오늘은 무엇을 하셨나요?"
    }))
    
    # 2. add attitude of input field

    class Meta:
        model = Post
        fields = ['content', 'image']
        
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(widget = forms.TextInput(attrs={
       'placeholder': '댓글을 입력하세요.',
       'class': 'form-control d-inline col-8'
   }), label='')
    
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import Post, Comment
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q


# Create your views here.
@login_required
def create(request):
    if request.method == "POST":
        # store written post in DB
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:list')
    else:
        # return form to write form
        form = PostForm()
        return render(request, 'posts/create.html', {'form': form})


def get_follower_posts(followers, posts):
    for follower in followers:
        posts = posts.union(follower.post_set.all())
    
    return posts
    
    
@login_required
def list(request):
    # show all post
    
    if request.user.is_authenticated:
        # 1. 직관적인 방법
        # posts = request.user.post_set.all()
        # followers = request.user.followings.all()
        # posts = get_follower_posts(followers, posts)
        
        # 2. field lookup 사용
        # posts = Post.objects.filter(user_id__in=request.user.followings.all())
        # my_posts = request.user.post_set.all()
        # posts=posts.union(my_posts)
        
        # 3. Q object 사용
        posts = Post.objects.filter(Q(user_id__in=request.user.followings.all()) | Q(user=request.user))
        
        comment_form = CommentForm()
        
        context = {}
        context['posts'] = posts
        context['comment_form'] = comment_form
        
        return render(request, 'posts/list.html', context=context)
    else:
        return redirect('accounts:login')
    


@require_POST
def delete(request, post_num):
    post = get_object_or_404(Post, pk=post_num)
    
    if post.user != request.user:
        return redirect('posts:list')
    
    post.delete()
    
    return redirect('posts:list')
    

def update(request, post_num):
    post = get_object_or_404(Post, pk=post_num)
    
    if post.user != request.user:
        return redirect('posts:list')
    
    if request.method == 'GET':
        form = PostForm(instance=post)
        
        context = {}
        context['form'] = form
        
        return render(request, 'posts/update.html', context=context)
    else:
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
            

@login_required
def like(request, post_num):
    # 1. get Post to like
    post = get_object_or_404(Post, pk=post_num)
    
    # 2. the user already liked this post, 
    #       remove like
    #    else
    #       add like
    
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    
    return redirect('posts:list')

@require_POST
@login_required
def create_comment(request, post_num):
    post = get_object_or_404(Post, id=post_num)
    
    form = CommentForm(request.POST)
    
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.post = post
        instance.save()
    
    return redirect('posts:list')


@require_POST    
@login_required
def delete_comment(request, post_num, comment_num):
    comment = get_object_or_404(Comment, id=comment_num)
    
    if request.user == comment.user:
        comment.delete()
        
    return redirect('posts:list')
    
    

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
  <!-- model form -->
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
    <div class="row justify-content-center">
      
      <!-- user posts 출력 -->
      {% if posts %}
        {% for post in posts %}
          <div class="card" style="width: 40rem;">
            <div class="card-header">
              <span><a href="{% url 'people' post.user.username  %}">{{ post.user }}</a></span>
            </div>
            
            <img src="{{ post.image.url }}" class="card-img-top" alt="...">
            
            <div class="card-body">
              <p class="card-text">{{ post.content }}</p>
              
              <!-- only writer can delete/update-->
              {% if post.user == request.user %}
              <div style="display: flex">
                <form action="{% url 'posts:delete' post.id %}" method="POST" class="mr-3">
                  {% csrf_token %}
                  <input type="submit" value="delete" class="btn btn-danger"/>
                </form>
                <form action="{% url 'posts:update' post.id %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="edit" class="btn btn-success"/>
                </form>
              </div>
              {% endif %}
              
            </div>
            
            
            <!--like button-->
            <div class="card-body">
              <a href="{% url 'posts:like' post.id %}" class="side-menu">
                {% if user in post.like_users.all %}
                  <i class="fas fa-heart like"></i>
                {% else %}
                  <i class="far fa-heart"></i>
                {% endif %}
              </a>
              <p class="card-text">
                {{ post.like_users.count }}명이 좋아합니다.
              </p>
              
              <div class="card-body">
                <!--Comment에 대한 ModelForm-->
                <form action="{% url 'posts:create_comment' post.id %}" method="POST">
                  {% csrf_token %}
                  <!--bootstrap_form-->
                  {{ comment_form }}
                  <button type="submit" class="btn btn-info">comment</button>
                </form>
                
                
                <!--해당 글의 모든 comment 출력-->
                {% for comment in post.comment_set.all %}
                  <p>
                    <strong>{{ comment.user.username }}</strong> {{ comment.content }} 
                    {% if request.user == comment.user %}
                    <form action="{% url 'posts:delete_comment' post.id comment.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">delete</button>
                    </form>
                    {% endif %}
                    </p>
                
                {% empty %}    
                  <div><strong>Take me your comment</strong></div>
                {% endfor %}
              </div>
                
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>

{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}